name: Build e Push Docker (versão automática)

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build & push da imagem com tag automática
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: patrickserafim/versionamento
          registry: docker.io
          tags: |
            latest
          appendMode: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
